shell.run("wget run https://raw.githubusercontent.com/sena5641/ai_bot_cc/refs/heads/main/load.lua")
-- shell.run("wget run ")
-- shell.run("wget run ")
-- shell.run("wget run ")
-- shell.run("wget run ")
